name: Build and Publish

on:
  push:
    branches:
      - main  # ou outro branch de sua escolha
  workflow_dispatch:

jobs:

  build:
    name: Build
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with maven
        run: mvn package --file pom.xml
      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        env:
          JAVA_HOME: /opt/jdk
        id: Depcheck
        with:
          project: 'test'
          path: '.'
          format: 'HTML'
          out: 'reports' # this is the default, no need to specify unless you wish to override it
          #args: >
            #--failOnCVSS 7 # o gate falha quando vulnerabilidade >= 7
            #--enableRetired
      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
           name: Depcheck report
           path: ${{github.workspace}}/reports


  sonarQube:
    name: Sonar
    needs: build
    runs-on: self-hosted
    
    steps:
      - name: Maven Build
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar

  publish:
    name: Publish Nexus
    needs: sonarQube
    runs-on: self-hosted
    steps:
      - name: Teste de Conectividade Nexus
        run: |
          curl -I http://localhost:8081
      - name: Nexus Repository Publish
        run: mvn clean deploy
        
