name: SonarQube Analysis

on:
  push:
    branches:
      - main  # ou outro branch de sua escolha

jobs:
  sonarQube:
    runs-on: self-hosted
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run Sonar Scanner
        env:
          SONAR_HOST_URL: http://localhost:9000  # URL do SonarQube local
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Token de autenticação
        run: |
          sonar-scanner \
            -Dsonar.projectKey=dev-sonar-actions \
            -Dsonar.sources=. \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.login=$SONAR_TOKEN
            -Dsonar.version=0.0.4-RC
