name: Build and Publish

on:
  push:
    branches:
      - main  # ou outro branch de sua escolha

jobs:

  build:
    name: Build
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with maven
        run: mvn package --file pom.xml

  sonarQube:
    name: Sonar
    needs: build
    runs-on: self-hosted
    
    steps:
      - name: Maven Build
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar

  publish:
    name: Publish Nexus
    needs: sonarQube
    runs-on: self-hosted
    steps:
      - name: Nexus Repo Publish
        uses: sonatype-nexus-community/nexus-repo-github-action@master
        with:
          serverUrl: http://http://localhost:8081
          username: ${{ vars.NEXUS_USERNAME }}
          password: ${{ secrets.NEXUS_PASSWORD }}
          format: maven2
          repository: devops-maven-snapshot
          coordinates: groupId=br.com.devsenior artfactId=dev-sonar-actions version=0.0.2
          assets: extension=jar
          filename: ./target/dev-sonar-actions.jar
        
