name: SonarQube Analysis

on:
  push:
    branches:
      - main  # ou outro branch de sua escolha

jobs:
  sonarQube:
    runs-on: self-hosted
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Maven Build
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
        
